### PR TITLE
Fixes dependency declarations and uses new api.addAssets

### PR DESCRIPTION
**Pull request by lourd**
- Adds jquery, underscore, and tracker declarations that were absent before
- Removes ui and spacebars declarations that weren't actually used
- Drops the architecture specifications for api.use since it doesn't
actually do anything
- Uses api.addAssets in accordance with the new 1.2 packaging API

### CODE REVIEW

**Comment by marcodejongh** [comment]
@lourd  I've checked out your fork and tried to use that to run my tests.

I get the following stylus error:
```
mojong$ meteor test-packages --velocity --driver-package respondly:test-reporter --port 10015 --once
=> Build failed:

   While building package respondly:test-reporter:
   error: Stylus compiler error: client/ctrls/tr-result-suite/tr-result-suite.styl:1
   > 1| @import 'core.import'
   2|
   3|
   4| .tr-result-suite

   failed to locate @import file core.import.styl

   error: Stylus compiler error:
   /Users/mojong/Projects/meteor/skunk/app/packages/meteor-test-reporter/client/css-mixins/test-runner.import.styl:1
   > 1| @import 'core.import'
   2|
   3|
   4| $TR_FONT_SANS = 'Helvetica Neue', Helvetica, Arial, sans-serif

   failed to locate @import file core.import.styl
```

**Comment by marcodejongh** [comment]
Actually scratch that I needed more of the dependencies to be updated.
So workaround until all PR's are merged and released:

1. Checkout:
```
git@github.com:lourd/meteor-test-reporter.git
git@github.com:Respondly/meteor-ctrl.git
git@github.com:Respondly/meteor-util.git
git@github.com:lourd/meteor-css-common.git
```
2. Setup symlinks in the package directory of the app you're running the tests from.
3. Comment out the onTest functions in the package.js' of the packages that where checked out.

**Comment by philcockfield** [comment]
Hey there @marcodejongh - I'll attempt to get all these merged in today.  Thanks.

**Comment by poltorak** [comment]
Is anybody going to fix and merge this?

**Comment by philcockfield** [comment]
Sorry for delay - been traveling.  Looking at this now.

**Comment by philcockfield** [comment]
Dealing with some issues, given Respondly hasn't gone up to `1.2.0.2` yet...hold tight.  Apologies for the delay.

**Comment by philcockfield** [comment]
So here's an update - we've got a bunch of dependencies that are a little tricky given we are using PACKAGE_DIRS internally to reference packages.  The team has been travelling, so something is going to take a look at this on Monday.

**Comment by dmitrijs-balcers** [comment]
This is quite urgent for me as well, do you guys need any help?

**Comment by philcockfield** [comment]
@hharnisc - are you just about ready to do the merge of this?

**Comment by hharnisc** [comment]
Thanks for the PR @lourd - still working out a couple of issues in the lower level dependencies. I expect to have this fixed by EOD or tomorrow morning at the latest. CC @dmitrijs-balcers @philcockfield @poltorak @marcodejongh

**Comment by lorensr** [comment]
+1 :)

**Comment by dmitrijs-balcers** [comment]
@hharnisc is this reporter supposed to work with `Meteor 1.2`?

**Comment by hharnisc** [comment]
@dmitrijs-balcers yes, this should work with 1.2

an update on my last comment - I updated and published the underlying packages that `test-reporter` depends on last week. Everything was working nicely locally but then I had an issue with the stylus compiler when publishing. I've passed it on to my teammate @philcockfield to take a look.

Sorry guys I really want to get this updated so it will work as expected with Meteor 1.2

**Comment by dmitrijs-balcers** [comment]
@hharnisc I see, thank you for an update

**Comment by philcockfield** [comment]
@dmitrijs-balcers @hharnisc - one little publish SNAFU Harrison and I are dealing with and we should be good to go.

**Comment by poltorak** [comment]
Hi guys! Is any progress with that? This package is quite urgent for me as well. When it will be available for meteor 1.2?

**Comment by timhaines** [comment]
@philcockfield Are you familiar with what actually needs to be changed to resolve the Stylus compiler errors?

**Comment by philcockfield** [comment]
@poltorak a new version (`1.0.2`) has not been published which works against Meteor 1.2.

Apologies for the delay on this.  A comedy of errors getting this up to Meteor 1.2.

**Comment by poltorak** [comment]
@philcockfield thank you! Meteor 1.2 brings a lot of comedy errors, don't worry :)

**Comment by poltorak** [comment]
@philcockfield can you also push change on master branch?

**Comment by philcockfield** [comment]
They have been pushed: https://github.com/Respondly/meteor-test-reporter/commit/5b2e0ffda7f12d6f5a4c8c08fb5755e011e7af99

Are you seeing something different?

**Comment by poltorak** [comment]
When I run command `meteor test-packages --driver-package respondly:test-reporter` and go localhost:3000 I still got error `Uncaught TypeError: $ is not a function`. Is this test reporter or I am doing something wrong?

**Comment by philcockfield** [comment]
Hmmm - pulling @hharnisc and @rissem back in.  This is working within our environment, but obviously something is still weird.

I'm actually not hands on with this code these days, hence referencing @hharnisc and @rissem

**Comment by rissem** [comment]
@poltorak Try using `meteor test-packages --driver-package respondly:test-reporter@1.0.1` Pretty sure it's falling back to an old version for some reason when it's not explicitly specified. I'll look into this more in the not too distant future.

**Comment by marcodejongh** [comment]
@rissem @philcockfield Now local runs work but running on CI is broken :cry: https://github.com/Respondly/meteor-test-reporter/issues/43

**Pull request closed without merging**
